### ISSUE TITLE
Cannot run a trial experiment

### ISSUE THREAD

**Issue by sun8608** [bioidiap/bob.bio.spear#1]
Hello! I was just trying to run a trial experiment using Voxforge database following the instruction of manuals: sudo /usr/local/bin/verify.py -vv -d voxforge -p energy-2gauss -e mfcc-60 -a gmm-voxforge -s ubm_gmm --groups {dev,eval}

 but I kept getting the error message:  
bob.bio.base@2015-08-01 11:03:15,971 -- INFO: - Preprocessing: processing 6561 data files from directory '[YOUR_VOXFORGE_WAV_DIRECTORY]' to directory 'temp/ubm_gmm/preprocessed'
bob.bio.base@2015-08-01 11:03:15,975 -- ERROR: During the execution, an exception was raised: [Errno 2] No such file or directory: '[YOUR_VOXFORGE_WAV_DIRECTORY]/ColinBeckingham-20091029-hfv/wav/a0001.wav'
Traceback (most recent call last):
  File "/usr/local/bin/verify.py", line 9, in <module>
    load_entry_point('bob.bio.base==2.0.1', 'console_scripts', 'verify.py')()
  File "build/bdist.linux-x86_64/egg/bob/bio/base/script/verify.py", line 435, in main

  File "build/bdist.linux-x86_64/egg/bob/bio/base/script/verify.py", line 415, in verify

  File "build/bdist.linux-x86_64/egg/bob/bio/base/script/verify.py", line 255, in execute

  File "build/bdist.linux-x86_64/egg/bob/bio/base/tools/preprocessor.py", line 58, in preprocess
  File "build/bdist.linux-x86_64/egg/bob/bio/spear/preprocessor/Base.py", line 21, in read_original_data
  File "/usr/lib/python2.7/dist-packages/scipy/io/wavfile.py", line 108, in read
    fid = open(file, 'rb')
IOError: [Errno 2] No such file or directory: '[YOUR_VOXFORGE_WAV_DIRECTORY]/ColinBeckingham-20091029-hfv/wav/a0001.wav'

I do not know where I can change the config file, I cannot find a folder with name 'config', there is one 'config' folder in under bob spear installation directory, but changing configuration of this one did not solve my problem; also the directory--build/bdist.linux-x86_64/ is actually empty, I do not know how the messages are retrieved.

**Comment by laurentes** [comment]
Hello,

You have to indicates to the script where to find the VoxForge data.
See here: 
http://pythonhosted.org/bob.bio.spear/baselines.html#setting-up-your-database
and here: 
https://pythonhosted.org/bob.bio.base/installation.html#bob-bio-base-installation

Cheers,
Laurent

**Comment by sun8608** [comment]
Yes, I was trying to tell the system where to find the wav files but did not know how to do it. I tried to created the file 'bob_bio_databases.txt' and notified the path: '[YOUR_VOXFORGE_WAV_DIRECTORY]=path/to/files' but this did not work, also when I tried to run '/bin/databases.py' I got the error message: 
raise RuntimeError('Invalid directory specified %s.' % (self.m_base_dir))
RuntimeError: Invalid directory specified /home/local/ANT/hechasun/bob/bio/spear/config/database/banca
There is just no bob folder in the home directory.

**Comment by siebenkopf** [comment]
First of all, the file is called ``.bob_bio_databases.txt`` (you are missing a ``.``) and it needs to be located in your HOME directory.
Anyways, the error message should not appear. Could you please provide us with the full error trace, so that we can trace the error?

Thanks
Manuel

**Comment by sun8608** [comment]
Changed the filename by adding ',' now it is working, thank you very much! Just one more question, if I want to adapt to my own database, do I just need to change those "lst" files and put my wav files into the same folder or I have to do something else?

**Comment by siebenkopf** [comment]
You can modify the file lists of the database or create your own database as explained here:
http://pythonhosted.org/bob.bio.base/implementation.html#databases

As your issue is fixed, I close this bug.

**Comment by sun8608** [comment]
Hi, I am a newbie in CS engineering and had great difficulty in implementing my own experiments--I have modified the file lists of Voxforge database but I still cannot run the pipelines, I think I need to change other config files also but I do not know which, could you please help me?

**Comment by sun8608** [comment]
Hi, I am sorry but I am in a really urgent situation to run this experiment. I was trying to edit file lists of existing database to run my own experiment, but it did not work, it seemed still search those old files, I think there are other config files I need to change but I cannot find them, please help and thanks very much!

**Comment by siebenkopf** [comment]
From your error description it is really difficult for us to find out, what is your issue. From your explanation, I cannot figure out, what possibly might have gone wrong, and how we could help you to run the experiment. Please be more specific in your error description. What was the exact steps that you were taking? What is the exact error message that you are getting? Which files were you editing, and what is their new content?

**Comment by sun8608** [comment]
Hi, I was trying to modify the existing database Voxforge to run my own experiment 
I have the following folders in my base dir:
dev  eval  norm  preprocessed
Where I just modified the corresponding file lists in Voxforge database--train_world.lst, for_models.lst and for_probes.lst, in the preprocessed folder I have the preprocessed hdf5 files included in those file lists. Then I ran the following commands:
sudo /usr/local/bin/verify.py -vv -d voxforge -p energy-2gauss  --skip-preprocessing --preprocessed-directory ./preprocessed -e mfcc-60 -a ivector -s ivector_test --groups eval

Ideally it should just work, but I got the following message:
RuntimeError: HDF5File - hdf5 constructor: C++ exception caught: 'cannot open file `/home/local/ANT/hechasun/voxforge/lists/preprocessed/ColinBeckingham-20091029-hfv/wav/a0001.hdf5
While the file "ColinBeckingham-20091029-hfv/wav/a0001.hdf5" is one sample data file in the original Voxforge database, it seemed the program was still searching Voxforge sample data files instead of my own data files, I am wondering how I can tell the program to run pipelines on my own data files. 

Hope this can clarify my problem. 
Thank you!

**Comment by siebenkopf** [comment]
Now, we are getting closer. I think that your problem is that the train_world.lst, for_models.lst and for_probes.lst are not in the folder, in which the database configuration file is set to.

Instead of modifying the files for the Voxforge database, I would recommend to create your own bob.db.verification.filelist database, as explained here:
http://pythonhosted.org/bob.db.verification.filelist/guide.html#creating-file-lists
(I think you have already done most of the steps)
create a configuration file as explained here:
http://pythonhosted.org/bob.bio.base/implementation.html#configuration-files
(for an example filelist database, look here: https://github.com/bioidiap/bob.bio.base/blob/master/bob/bio/base/test/dummy/filelist.py)
and use this configuration file in your experiment:
http://pythonhosted.org/bob.bio.base/more.html#running-experiments-part-ii

I hope this helps. Unfortunately, it seems that the structure of creating new databases is still not well documented. We are regularly improving our documentation, partially based on comments of the users. However, as the main focus of the bob.bio packages lies on using well-developed and pre-defined databases to run comparable experiments, the support for using privately defined databases is limited.

**Comment by sun8608** [comment]
It's very helpful, thank you very much!

**Comment by sun8608** [comment]
Hello! I got the following error when I was running my experiment: 

ERROR: During the execution, an exception was raised: bob.learn.em.GMMMachine - cannot accumulate the statistics: C++ exception caught: 'logadd: minusdif (-nan) log_b (-nan) or log_a (-179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000) is nan'

I was using the default setting for ivector algorithm (with dimensions 512/400) and 6k sample untterances for UBM training, the preprossesor and extractor I was using are energy-thr and mfcc-60; And when I tried with fewer UBM samples--500 and lower ivector dimensions 50/20, I got the same error message. It seems that the statistics cannot be computed but I cannot find a valid reason for this, I ran it successfully with another small batch of sample though, is it because some of the data is corrupted? 
Thank you!

**Comment by tiagofrepereira2012** [comment]
Hi,

Check the means and the variances of your UBM.
Maybe you will find some NaN there.

Cheers

Tiago

On Tue, Aug 11, 2015 at 5:22 PM, sun8608 <notifications@github.com> wrote:

> Hello! I got the following error when I was running my experiment:
>
> ERROR: During the execution, an exception was raised:
> bob.learn.em.GMMMachine - cannot accumulate the statistics: C++ exception
> caught: 'logadd: minusdif (-nan) log_b (-nan) or log_a
> (-179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000)
> is nan'
>
> I was using the default setting for ivector algorithm (with dimensions
> 512/400) and 6k sample untterances for UBM training, the preprossesor and
> extractor I was using are energy-thr and mfcc-60; And when I tried with
> fewer UBM samples--500 and lower ivector dimensions 50/20, I got the same
> error message. It seems that the statistics cannot be computed but I cannot
> find a valid reason for this, I ran it successfully with another small
> batch of sample though, is it because some of the data is corrupted?
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bioidiap/bob.bio.spear/issues/1#issuecomment-129928308>
> .
>



-- 
Tiago

**Comment by sun8608** [comment]
Hi, how can I check the statistics of the UBM? These are all hdf5 files.

**Comment by tiagofrepereira2012** [comment]
Hey,

You can inspect using the bob API.
Look the following script

import bob.learn.em
import bob.io.base
gmm =
bob.learn.em.GMMMachine(bob.io.base.HDF5File("<YOUR_UBM_FILE_HERE.hdf5>"))
#Now you can inspect the GMM content (means, diagonal covariance and
weights)

Cheers
Tiago






On Tue, Aug 11, 2015 at 6:04 PM, sun8608 <notifications@github.com> wrote:

> Hi, how can I check the statistics of the UBM? These are all hdf5 files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bioidiap/bob.bio.spear/issues/1#issuecomment-129949180>
> .
>



-- 
Tiago

**Comment by sun8608** [comment]
Hi, is the UBM file supposed to be "Projector.hdf5"? But it says "Cannot find dataset `m_n_gaussians' at `Projector.hdf5"

**Comment by tiagofrepereira2012** [comment]
Hey,

Try this code, I think spear stores the UBM and the T Matrix in the same
file ('Projector.hdf5')

import bob.learn.em
import bob.io.base
hdf5 = bob.io.base.HDF5File("<YOUR_UBM_FILE_HERE.hdf5>")
hdf5.cd('Projector')
gmm = bob.learn.em.GMMMachine(hdf5)
#Now you can inspect the GMM content (means, diagonal covariance and
weights)

On Tue, Aug 11, 2015 at 6:26 PM, sun8608 <notifications@github.com> wrote:

> Hi, is the UBM file supposed to be "Projector.hdf5"? But it says "Cannot
> find dataset m_n_gaussians' atProjector.hdf5"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bioidiap/bob.bio.spear/issues/1#issuecomment-129955635>
> .
>



-- 
Tiago

**Comment by sun8608** [comment]
Hi, I checked with:
v=gmm.means_supervector, m=gmm.mean_supervector, but I got math.isnan(any(v))=False and math.isnan(any(m))=False, it seems that none of them are NaNs

**Comment by sun8608** [comment]
Any other suggestions? Please

**Comment by tiagofrepereira2012** [comment]
Hey,

Check all the gaussian components (variances and weights).
And of course, your inputs.

It seems that your issue is the accumulation of the log likelihood (
https://github.com/bioidiap/bob.learn.em/blob/master/bob/learn/em/cpp/GMMMachine.cpp#L247
).

Which database are you using?

Cheers





On Tue, Aug 11, 2015 at 8:53 PM, sun8608 <notifications@github.com> wrote:

> Any other suggestions? Please
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bioidiap/bob.bio.spear/issues/1#issuecomment-130016486>
> .
>



-- 
Tiago

**Comment by sun8608** [comment]
Hi, the variances and weights look fine, I am using phone call data with two separate channels: converting from mp3 files to wav files, extracting the first channel, then preprocessing with energy-thr and extracting with mfcc-60, which of the above step could possibly cause the problem? Is it because of the data quality?

**Comment by smarcel** [comment]
Hi

thanks for your interest in spear.

For our records and stats, could you please answer these 3 quick questions ?
1. how did you learn about BOB or SPEAR ?
2. in which context do you want to use it ?
3.a are you a student or researcher ? in which University / Research Institution ?
3.b are you an engineer ? in which company ?

best regards

Sébastien

**Comment by siebenkopf** [comment]
I remember having these kind of issues as well. In my case, k-means was not working properly, when I used the wrong initialization method (``RANDOM``). With ``KMEANS_PLUS_PLUS`` (see http://pythonhosted.org/bob.learn.em/py_api.html#bob.learn.em.KMeansTrainer), it was working better. More training data or less dimensions or Gaussians also helped sometimes.

However, your error might be at a different stage. Could you please post the **complete error backtrace** that you are getting, so that we might get a glance on where your issue appears?

@tiagofrepereira2012 For you to note, the exact command line and the error backtrace should always be the first things to ask for. Otherwise you might to try to fix issues at places where they do not exist... :-)

**Comment by sun8608** [comment]
Hi, @smarcel:
I learn about bob.spear from recommendation of others, I am a graduate student involving an intern project concerning recording data in a company, I am just trying to run some prototype experiments to see how well it performs, my main job is to set up the pipelines correctly I think. 

@siebenkopf 
For me I think I already have a large training data ~6k records and I ran with lower dimension 50/20, but the same error still appeared. 
The full error trace is:
ERROR: During the execution, an exception was raised: bob.learn.em.ML_GMMTrainer - cannot perform the e_step method: C++ exception caught: 'logadd: minusdif (-nan) log_b (-nan) or log_a (-179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000) is nan'
Traceback (most recent call last):
  File "/usr/local/bin/verify.py", line 9, in <module>
    load_entry_point('bob.bio.base==2.0.1', 'console_scripts', 'verify.py')()
  File "build/bdist.linux-x86_64/egg/bob/bio/base/script/verify.py", line 435, in main

  File "build/bdist.linux-x86_64/egg/bob/bio/base/script/verify.py", line 415, in verify

  File "build/bdist.linux-x86_64/egg/bob/bio/base/script/verify.py", line 278, in execute

  File "build/bdist.linux-x86_64/egg/bob/bio/base/tools/algorithm.py", line 52, in train_projector
  File "build/bdist.linux-x86_64/egg/bob/bio/gmm/algorithm/IVector.py", line 88, in train_projector
  File "build/bdist.linux-x86_64/egg/bob/bio/gmm/algorithm/GMM.py", line 128, in train_ubm
  File "/usr/local/lib/python2.7/dist-packages/bob.learn.em-2.0.4-py2.7-linux-x86_64.egg/bob/learn/em/train.py", line 40, in train
    trainer.e_step(machine, data)
RuntimeError: bob.learn.em.ML_GMMTrainer - cannot perform the e_step method: C++ exception caught: 'logadd: minusdif (-nan) log_b (-nan) or log_a (-179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000) is nan'

Also when I did extraction, I finished with the message:
/usr/local/lib/python2.7/dist-packages/bob.bio.spear-2.0.3-py2.7.egg/bob/bio/spear/utils/__init__.py:131: RuntimeWarning: invalid value encountered in divide
Is this related to the error above? Thank you!

**Comment by siebenkopf** [comment]
Yes, I am pretty sure that this warning is causing the trouble. I assume that your input data is invalid. When you have a look at the code for the warning:
https://github.com/bioidiap/bob.bio.spear/blob/master/bob/bio/spear/utils/__init__.py#L131
you can see that it divides by the standard deviation of the data, which seems to be 0 in your case. Hence, the variance in one or more dimensions of your data is 0. You should have a look at that.

On the other hand, it seems that you might mix up experiments. In fact, since your error is in the projector training, you should not have a ``Projector.hdf5`` at all. Please verify that you run each experiment with a different configuration in a separate folder, i.e., by specifying a different ``--sub-directory`` for each experiment.

**Comment by sun8608** [comment]
Thank you! I also think there are some data quality issues here, but I cannot find which. It seems even I got the error message "RuntimeWarning: invalid value encountered in divide" when I did feature extraction from preprocessed data, the program will still finish the extraction without stopping, therefore I will not able to know which data file is corrupted. Do you have any suggestions on this?

**Comment by siebenkopf** [comment]
Indeed, it might not be that easy to find out, which data file is corrupted. You can try to use the standard Linux and HDF5 tools, such as explained here:
http://pythonhosted.org/bob.io.base/guide.html#user-guide
Maybe a combination of ``find``, ``h5dump`` and ``grep`` could be used to find corrupted data in your ``preprocessed`` directory.

The problem is that the warning message is issued by the standard Python utilities, and we have no control over that. As it is only a warning message, the computation doesn't stop there. However, it might be that it can be set up that warning messages should be handled as errors. Unfortunately, I don't have experience with that.
